destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    true
permalink:   date
markdown:    rdiscount
author:
  name:      Kerry Wilson
  email:     kwilson@goodercode.com
  github:    webdevwilson
  twitter:   webdevwilson
  feedburner: nil